apiVersion: v1
kind: Namespace
metadata:
  name: mlops

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
  namespace: mlops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
      - name: mlflow
        image: python:3.10-slim
        command: ["sh","-c"]
        args:
          - pip install mlflow psycopg2-binary && mlflow server --backend-store-uri postgresql://mlflowuser:ChangeMe123!@127.0.0.1:5432/mlflow --default-artifact-root gs://your-project-id-ml-models --host 0.0.0.0 --port 5000
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: mlflow
  namespace: mlops
spec:
  type: LoadBalancer
  selector:
    app: mlflow
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
